#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

#
## What version of liferay is currently getting deployed
#
_LIFERAY_PORTAL_DEPLOYING=`head -1 $OPENSHIFT_REPO_DIR/.openshift/action_hooks/deploying-war-info`

#
## What version of liferay is already deployed
#
_LIFERAY_PORTAL_DEPLOYED=""

#
## Liferay Portal deployment directory, its the core portal and not the plugins
#
_LIFERAY_PORTAL_DEPLOY_DIR="${OPENSHIFT_REPO_DIR}/webapps"

#
## Create the directory if it does not exist
#
if [ ! -d "$_LIFERAY_PORTAL_DEPLOY_DIR/$_LIFERAY_PORTAL_DEPLOYING" ]
 then   
   echo "Creating Liferay Portal Dir $_LIFERAY_PORTAL_DEPLOY_DIR"
   mkdir -p "$_LIFERAY_PORTAL_DEPLOY_DIR/$_LIFERAY_PORTAL_DEPLOYING"
fi

#
## The directory where all you customizations are placed things like portal-ext.properties, log4j-ext.xml etc.,
#
_CUSTOMIZATION_DIR="${OPENSHIFT_REPO_DIR}/customization"

if [ -f "${OPENSHIFT_DATA_DIR}/deployed-war-info" ]
 then
  _LIFERAY_PORTAL_DEPLOYED=`head -1 ${OPENSHIFT_DATA_DIR}/deployed-war-info`
   echo "Last deployed WAR : ${_LIFERAY_PORTAL_DEPLOYED}"
fi

# Download the Liferay Portal War
if [ "$_LIFERAY_PORTAL_DEPLOYING" = "$_LIFERAY_PORTAL_DEPLOYED" ]
 then
   echo "Portal already downloaded, unzipping and updating portal-*.properties"
   cd ${_LIFERAY_PORTAL_DEPLOY_DIR}/${_LIFERAY_PORTAL_DEPLOYING}
   if [ -f ${OPENSHIFT_TMP_DIR}/${_LIFERAY_PORTAL_DEPLOYING} ]
    then
       echo "Extracting the Liferay Portal ${_LIFERAY_PORTAL_DEPLOYING} as default application ROOT.war"
       jar -xvf ${OPENSHIFT_TMP_DIR}/${_LIFERAY_PORTAL_DEPLOYING}
   fi	
   cp -ra ${_CUSTOMIZATION_DIR}/ROOT.war/* ${_LIFERAY_PORTAL_DEPLOY_DIR}/$_LIFERAY_PORTAL_DEPLOYED
   cp -urv ${OPENSHIFT_REPO_DIR}/.openshift/action_hooks/ROOT.xml ${OPENSHIFT_JBOSSEWS_DIR}/conf/Catalina/localhost/ROOT.xml
   echo "Portal properties/configuration successfully updated, please access the portal after 2-5 minutes"
   
 else
   echo "Downloading Liferay Portal : ${_LIFERAY_PORTAL_DEPLOYING}"
   cd ${OPENSHIFT_TMP_DIR}
   #Downlad the war
   wget -O ${_LIFERAY_PORTAL_DEPLOYING}  -v "http://sourceforge.net/projects/lportal/files/Liferay%20Portal/6.2.1%20GA2/${_LIFERAY_PORTAL_DEPLOYING}"
   cd ${_LIFERAY_PORTAL_DEPLOY_DIR}/${_LIFERAY_PORTAL_DEPLOYING}
   if [ -f ${OPENSHIFT_TMP_DIR}/${_LIFERAY_PORTAL_DEPLOYING} ]
    then
       echo "Extracting the Liferay Portal ${_LIFERAY_PORTAL_DEPLOYING} as default application ROOT.war"
       jar -xvf ${OPENSHIFT_TMP_DIR}/${_LIFERAY_PORTAL_DEPLOYING}
   fi
   # update configurations
   echo "Update the custom configuration files like portal-*.properties, log4j-ext etc.,"
   cp -urv ${_CUSTOMIZATION_DIR}/ROOT.war/* ${_LIFERAY_PORTAL_DEPLOY_DIR}/${_LIFERAY_PORTAL_DEPLOYING}
   cp -urv ${OPENSHIFT_REPO_DIR}/.openshift/action_hooks/ROOT.xml ${OPENSHIFT_JBOSSEWS_DIR}/conf/Catalina/localhost/ROOT.xml
   # update the currently deployed war
   echo ${_LIFERAY_PORTAL_DEPLOYING} >> ${OPENSHIFT_DATA_DIR}/deployed-war-info
fi
